name: sell-art-docker
version: '3.8'

services:

  redis:
    restart: unless-stopped
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - 6379

  art_django_app:
    build:
      context: .
    image: djangoimage
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_app:
    image: djangoimage
    container_name: celery
    build:
      context: .
    entrypoint: /app/worker_entrypoint.sh
    command: celery -A eshopperproject worker -E -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - art_django_app

  beat:
    container_name: beat
    image: djangoimage
    command: celery -A eshopperproject beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
      - art_django_app

volumes:
  redis_data:
  static: #celery -A Ryvm_project.celeryapp worker --pool=solo -l INFO
