version: '3.8'

services:

  redis:
    restart: unless-stopped
    image: "redis:7.0.11-alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379

  art_django_app:
    build:
      context: .
    image: django-image
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/tradeconnect/static
    env_file:
      - .env
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
    depends_on:
      - redis

  celery_app:
    image: django-image
    container_name: celery
    command: celery --app=eshopperproject worker --pool=solo -l INFO
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - art_django_app

  beat:
    container_name: beat
    image: django-image
    command: celery -A eshopperproject beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - art_django_app

volumes:
  static: #celery -A Ryvm_project.celeryapp worker --pool=solo -l INFO
