# Generated by Django 4.2.14 on 2024-07-30 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artapp', '0010_remove_artproduct_profile_pic'),
        ('auction_app', '0002_alter_auctiongroupchat_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiongroupchat',
            name='Artproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artapp.artproduct'),
        ),
        migrations.AlterField(
            model_name='auctiongroupchat',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
