# Generated by Django 4.2.14 on 2024-07-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0010_remove_artproduct_profile_pic'),
        ('auction_app', '0004_alter_auctiongroupchat_artproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiongroupchat',
            name='Artproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artapp.artproduct'),
        ),
    ]
