# Generated by Django 4.2.14 on 2024-08-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction_app', '0006_auctiongroup_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctiongroup',
            name='user_online',
        ),
        migrations.AddField(
            model_name='auctiongroup',
            name='user_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_in_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
