# Generated by Django 4.2.9 on 2024-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0006_alter_artproduct_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
