# Generated by Django 4.2.14 on 2024-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0008_brand_artproduct_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/variac.jpeg/', null=True, upload_to='images'),
        ),
    ]
