# Generated by Django 4.2.14 on 2024-07-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0009_artproduct_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artproduct',
            name='profile_pic',
        ),
    ]
