# Generated by Django 4.2.14 on 2024-08-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0010_remove_artproduct_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='frame',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artproduct',
            name='height',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artproduct',
            name='length',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artproduct',
            name='weight',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artproduct',
            name='width',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
