# Generated by Django 4.2.14 on 2024-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0012_alter_artproduct_height_alter_artproduct_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='auction_activated',
            field=models.BooleanField(default=False),
        ),
    ]
