# Generated by Django 4.2.14 on 2024-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0014_artproduct_auction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproduct',
            name='auction_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
