# Generated by Django 4.2.14 on 2024-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0016_alter_artproduct_auction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproduct',
            name='auction_activated',
            field=models.CharField(choices=[('None', 'None'), ('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='STATUS[0]', max_length=200, null=True),
        ),
    ]
