# Generated by Django 4.2.14 on 2024-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0017_alter_artproduct_auction_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='auction_stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
