# Generated by Django 4.2.14 on 2025-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0018_artproduct_auction_stop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='homes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='artproduct',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
