# Generated by Django 4.2.14 on 2025-02-15 22:07

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0019_artproduct_homes_artproduct_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpicturemodel',
            name='file',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
