# Generated by Django 4.2.14 on 2025-02-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0020_alter_artpicturemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpicturemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
