# Generated by Django 4.2.14 on 2025-02-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0022_artproduct_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='individual_prints',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='artproduct',
            name='sets_of_prints',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
