# Generated by Django 4.2.9 on 2024-06-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custombaseuser',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='custombaseuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/variac.jpeg/', null=True, upload_to='images'),
        ),
    ]
