# Generated by Django 4.2.9 on 2024-06-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0001_initial'),
        ('userapp', '0002_rename_firstname_custombaseuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='artapp.artproduct'),
        ),
    ]
