# Generated by Django 4.2.9 on 2024-06-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_custombaseuser_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombaseuser',
            name='products',
        ),
    ]
