# Generated by Django 4.2.9 on 2024-06-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_custombaseuser_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='products',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
